---

#- name: prep setup
#  hosts: all
#  become: yes
#  roles:
#    - setup

#- name: install kube dependencies
#  hosts: all
#  become: yes
#  roles:
#    - kubedependencies

- name: setup kube master
  hosts: master
  become: yes
  roles:
    - master
