---

#- name: prep setup
#  hosts: all
#  become: yes
#  roles:
#    - setup

#- name: install kube dependencies
#  hosts: all
#  become: yes
#  roles:
#    - kubedependencies

- name: setup kube master
  hosts: master
  become: yes
  #  become_user: ubuntu
  roles:
    - master

- name: setup kube workers
  hosts: workers
  become: yes
  #become_user: ubuntu
  roles:
    - workers
