- name: add ubuntu user to group docker
  command: usermod -aG docker ubuntu

- name: enable docker
  command: systemctl unmask docker.service
  command: systemctl unmask docker.socket
  command: systemctl enable docker.service
  command: systemctl start docker.service

- name: Disable system swap
  shell: "swapoff -a"

- name: Remove current swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '(?i)^([^#][\S]+\s+(none|swap)\s+swap.*)'
    line: '# \1'
    backrefs: yes
    state: present

- name: run kubeadm init
  command: kubeadm init --pod-network-cidr=10.244.0.0/16

- pause:
    minutes: 1
    prompt: "Make sure admin pods are started"

- shell: kubeadm token create --print-join-command
  register: results
- debug:
    var: results.stdout
- set_fact:
    token: "{{ results.stdout | regex_search(regexp, '\\2') | first }}"
  vars:
    regexp: '([^\s]+\s){4}([^\s]+)'
- debug:
    var: token
- set_fact:
    hash: "{{ results.stdout | regex_search(regexp, '\\2') | first }}"
  vars:
    regexp: '([^\s]+\s){6}([^\s]+)'
- debug:
    var: hash

- name: allow permissive RBAC rules
  command: "kubectl --kubeconfig /etc/kubernetes/admin.conf create clusterrolebinding permissive-binding \
  --clusterrole=cluster-admin \
  --user=admin \
  --user=kubelet \
  --group=system:serviceaccounts"

- name: taint master node
  command: kubectl --kubeconfig /etc/kubernetes/admin.conf taint nodes --all node-role.kubernetes.io/master-

- name: install flannel pod network
  command: kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

- name: copy config file to HOME/.kube dir
  command: "{{ item }}"
  with_items:
    - mkdir -p ~ubuntu/.kube
    - cp /etc/kubernetes/admin.conf ~ubuntu/.kube/config
    - chown -R ubuntu:ubuntu ~ubuntu/.kube
    - chmod 0400 ~ubuntu/.kube/config

- pause:
    minutes: 1
    prompt: "Make sure network pods are started"
